module.exports = {
    servertype: {
        type: "string",
        description:
            'GDB Server type - supported types are jlink, openocd, pyocd, pe, stlink, stutil, qemu, bmp and external. For "external", [please read our Wiki](https://github.com/mcu-debug/mcu-debug/wiki/External-gdb-server-configuration). The executable in your PATH is used by default, to override this use serverpath.',
        enum: ["jlink", "openocd", "pyocd", "stutil", "stlink", "bmp", "pe", "qemu", "external"],
    },
    cwd: {
        description: "Directory to run commands from",
        type: "string",
    },
    debuggerArgs: {
        default: [],
        description: "Additional arguments to pass to GDB command line",
        type: "array",
        items: { type: "string" },
    },
    preLaunchCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Additional GDB Commands to be executed at the start of the main launch sequence (immediately after attaching to target).",
    },
    postLaunchCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Additional GDB Commands to be executed after the main launch sequence has finished.",
    },
    preAttachCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Additional GDB Commands to be executed at the start of the main attach sequence (immediately after attaching to target).",
    },
    postAttachCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Additional GDB Commands to be executed after the main attach sequence has finished.",
    },
    preResetCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Commands to be executed prior to a Reset operation, before the reset is sent to the target.",
    },
    postResetCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Commands to be executed after a Reset operation, after the reset is sent to the target.",
    },
    postRestartCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Deprecated: Restart is now handled by VSCode. Change to postResetCommands if you use the Reset button.",
        deprecationMessage: "Restart is now handled by VSCode. Change to postResetCommands if you use the Reset button.",
    },
    overrideLaunchCommands: {
        default: null,
        type: "array",
        items: { type: "string" },
        description: "Override the commands that are normally executed as part of flashing and launching the target.",
    },
    overrideAttachCommands: {
        default: null,
        type: "array",
        items: { type: "string" },
        description: "Override the commands that are normally executed as part of attaching to a running target.",
    },
    overrideRestartCommands: {
        default: null,
        type: "array",
        items: { type: "string" },
        description: "Deprecated: Restart is now handled by VSCode. Change to overrideResetCommands if you use the Reset button.",
        deprecationMessage: "Restart is now handled by VSCode. Change to overrideResetCommands if you use the Reset button.",
    },
    overrideResetCommands: {
        default: null,
        type: "array",
        items: { type: "string" },
        description: "Override the commands that are normally executed as part of reset-ing the target.",
    },
    postStartSessionCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Additional GDB Commands to be executed at the end of the start sequence, after a debug session has already started and runToEntryPoint is not specified.",
    },
    postResetSessionCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Additional GDB Commands to be executed at the end of the reset sequence",
    },
    postRestartSessionCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Deprecated: Restart is now handled by VSCode and it is the same as Start. If you are using the Reset button, use postResetSessionCommands instead",
        deprecationMessage: "Restart is now handled by VSCode and it is the same as Start. If you are using the Reset button, use postResetSessionCommands instead",
    },
    overridePreEndSessionCommands: {
        default: [],
        type: "array",
        items: { type: "string" },
        description: "Override the commands that are normally executed at the start of ending a debug session (e.g. when stopping debugging).",
    },
    overrideGDBServerStartedRegex: {
        description: "You can supply a regular expression to override the output from the GDB Server that is looked for to determine if the GDB Server has started.",
        type: "string",
        default: null,
    },
    cpu: {
        default: "cortex-m3",
        type: "string",
        description: "CPU Type Selection - used for QEMU server type",
        anyOf: [{ enum: ["cortex-m3", "cortex-m4"] }, { type: "string" }],
    },
    machine: {
        default: "lm3s811evb",
        type: "string",
        description: "Machine Type Selection - used for QEMU server type",
        anyOf: [{ enum: ["lm3s811evb", "lm3s6965evb", "mps2-an385"] }, { type: "string" }],
    },
    device: {
        default: "",
        description: "Target Device Identifier",
        type: "string",
    },
    rtos: {
        default: null,
        description:
            "RTOS being used. For JLink this can be Azure, ChibiOS, embOS, FreeRTOS, NuttX, Zephyr or the path to a custom JLink RTOS Plugin library. For OpenOCD this can be auto (recommended), FreeRTOS, ThreadX, chibios, Chromium-EC, eCos, embKernel, linux, mqx, nuttx, RIOT, uCOS-III, or Zephyr.",
        type: "string",
    },
    armToolchainPath: {
        default: null,
        description: "This setting can be used to override the armToolchainPath user setting for a particular launch configuration.",
        type: "string",
    },
    toolchainPrefix: {
        default: null,
        description: 'This setting can be used to override the toolchainPrefix user setting for a particular launch configuration. Default = "arm-none-eabi"',
        type: "string",
    },
    serverpath: {
        default: null,
        description: "This setting can be used to override the GDB Server path user/workspace setting for a particular launch configuration.",
        type: "string",
    },
    gdbPath: {
        default: null,
        description: "This setting can be used to override the GDB path user/workspace setting for a particular launch configuration.",
        type: "string",
    },
    objdumpPath: {
        default: null,
        description: "This setting can be used to override the objdump path user/workspace setting for a particular launch configuration.",
        type: "string",
    },
    serverArgs: {
        default: [],
        description: "Additional arguments to pass to GDB Server command line",
        type: "array",
        items: { type: "string" },
    },
    executable: {
        description: "Path of executable for symbols and program information. See also `loadFiles`, `symbolFiles`",
        type: "string",
    },
    loadFiles: {
        description: "List of files (hex/bin/elf files) to load/program instead of the executable file.",
        type: "array",
        items: { type: "string" },
        default: null,
    },
    symbolFiles: {
        description: "Array of ELF files to load symbols from instead of the executable file.",
        type: "array",
        items: {
            type: ["object", "string"],
            properties: {
                file: { type: "string", description: "Pathname of an ELF file for symbols" },
                offset: { type: ["number", "string"], description: "Optional offset to apply to all sections of the ELF file." },
                textaddress: { type: ["number", "string"], description: "Optional: Load the TEXT section at the specified 'textaddress'." },
                sections: {
                    type: "array",
                    items: {
                        type: "object",
                        properties: {
                            name: { type: "string", description: "Section name" },
                            address: { type: ["number", "string"], description: "Base address for section." },
                        },
                        required: ["name", "address"],
                    },
                },
            },
            required: ["file"],
        },
        default: null,
    },
    gdbInterruptMode: {
        default: "exec-interrupt",
        description: 'Whether GDB shall be interrupted using "exec-interrupt" (default) or by signaling "SIGINT"',
        type: "string",
        enum: ["exec-interrupt", "SIGINT"],
    },
    gdbTarget: {
        default: null,
        description: 'For externally (servertype = "external") controlled GDB Servers you must specify the GDB target to connect to.',
        type: "string",
    },
    runToMain: {
        type: "boolean",
        default: false,
        description: "Deprecated: please use 'runToEntryPoint' instead.",
        deprecationMessage: "Please use 'runToEntryPoint' instead.",
    },
    breakAfterReset: {
        default: false,
        type: "boolean",
        description: "Applies to Restart/Reset/Launch, halt debugger after a reset. Ignored if `runToEntryPoint` is used.",
    },
    runToEntryPoint: {
        description: "Applies to Launch/Restart/Reset, ignored for Attach. If enabled the debugger will run until the start of the given function.",
        type: "string",
        default: "main",
    },
    numberOfProcessors: {
        description: "Number of processors/cores in the target device.",
        type: "number",
        multipleOf: 1,
        minimum: 1,
        maximum: 10,
        default: 1,
    },
    targetProcessor: {
        description: "The processor you want to debug. Zero based integer index. Must be less than 'numberOfProcessors'",
        type: "number",
        multipleOf: 1,
        minimum: 0,
        maximum: 9,
        default: 0,
    },
    hardwareBreakpoints: {
        description: "WARNING: Force only HW breakpoints to be used.",
        type: "object",
        properties: {
            require: { type: "boolean", default: false, description: "If true, forces the use of hardware breakpoints" },
            limit: { type: "number", minimum: 0, multipleOf: 1, default: 0, description: "If limit > 0, enforce a limit on the number of hardware breakpoints that can be used" },
        },
    },
    hardwareWatchpoints: {
        description: "WARNING: Force only HW watchpoints to be used.",
        type: "object",
        properties: {
            require: { type: "boolean", default: false, description: "If true, forces the use of hardware watchpoints" },
            limit: { type: "number", minimum: 0, multipleOf: 1, default: 0, description: "If limit > 0, enforce a limit on the number of hardware watchpoints that can be used" },
        },
    },
    liveWatch: {
        description: "An object with parameters for Live Watch",
        properties: {
            enabled: { default: false, description: "Enable/Disable Live Watch. Only applies to OpenOCD", type: "boolean" },
            samplesPerSecond: { default: 2, description: "Maximum number of samples per second.", type: "number", multipleOf: 0.25, minimum: 0, maximum: 20 },
        },
        default: { enabled: true, samplesPerSecond: 4 },
    },
    chainedConfigurations: {
        description: "An object describing how additional configurations should be launched",
        type: "object",
        properties: {
            enabled: { default: true, description: "Enable/Disable entire set of chained configurations", type: "boolean" },
            detached: { default: false, description: "Related or independent server sessions.", type: "boolean" },
            lifecycleManagedByParent: { default: true, description: "Are Restart/Reset/Stop/Disconnect shared?", type: "boolean" },
            waitOnEvent: { enum: ["postStart", "postInit"], default: "postInit", description: "Event to wait for.", type: "string" },
            delayMs: { type: "number", description: "Default delay in milliseconds.", multipleOf: 1, minimum: 0, default: 5 },
            overrides: { default: {}, description: "Values to override/set in this child configuration.", type: "object" },
            inherits: { default: [], description: "List of properties to inherit from parent.", type: "array", items: { type: "string" } },
            launches: {
                type: "array",
                items: {
                    properties: {
                        name: { default: "", description: "Name of launch configuration.", type: "string" },
                        folder: { default: "", description: "Folder to use for this configuration.", type: "string" },
                        enabled: { default: true, description: "Enable/Disable this configuration", type: "boolean" },
                        detached: { default: false, description: "Related or independent server sessions.", type: "boolean" },
                        waitOnEvent: { enum: ["postStart", "postInit"], default: "postInit", description: "Wait for an event.", type: "string" },
                        delayMs: { type: "number", description: "Delay in milliseconds.", multipleOf: 1, minimum: 0, default: 5 },
                        lifecycleManagedByParent: { default: true, description: "Are Restart/Reset/Stop/Disconnect shared?", type: "boolean" },
                        overrides: { default: {}, description: "Values to override/set in this child configuration.", type: "object" },
                        inherits: { default: [], description: "List of properties to inherit from parent.", type: "array", items: { type: "string" } },
                    },
                },
            },
        },
        default: {
            enabled: true,
            waitOnEvent: "postInit",
            lifeCycleShared: true,
            launches: [{ name: "use EXACT name of chained configuration to launch", folder: "use full path or folder basename or leave empty" }],
        },
    },
    graphConfig: {
        description: "Description of how graphing can be done.",
        type: "array",
        items: {
            oneOf: [
                {
                    properties: {
                        annotate: { default: true, description: "Create annotations on the graph.", type: "boolean" },
                        label: { description: "Label for Graph", type: "string" },
                        maximum: { default: 65535, description: "Maximum value for the X-Axis", type: "number" },
                        minimum: { default: 0, description: "Minimum value for the Y-Axis", type: "number" },
                        plots: {
                            description: "Plot configurations.",
                            items: {
                                properties: {
                                    color: { pattern: "^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$", type: "string" },
                                    graphId: { description: "Graph Data Source Id for the plot.", type: "string" },
                                    label: { description: "A label for this data set", type: "string" },
                                },
                                required: ["graphId"],
                                type: "object",
                            },
                            type: "array",
                        },
                        timespan: { default: 30, description: "Length of time (seconds) to be plotted on screen.", type: "number" },
                        type: { enum: ["realtime"], type: "string" },
                    },
                    required: ["label", "plots", "minimum", "maximum"],
                    type: "object",
                },
                {
                    properties: {
                        label: { description: "Label for graph", type: "string" },
                        timespan: { default: 10, description: "The amount of time (seconds) that the XY Plot will show the trace for.", type: "number" },
                        type: { enum: ["x-y-plot"], type: "string" },
                        xGraphId: { description: "Graph Data Source Id for the X axis", type: "string" },
                        xMaximum: { default: 65535, description: "Maximum value on the X-Axis", type: "number" },
                        xMinimum: { default: 0, description: "Minimum value on the X-Axis", type: "number" },
                        yGraphId: { description: "Graph Data Source Id Port for the Y axis", type: "string" },
                        yMaximum: { default: 65535, description: "Maximum value on the Y-Axis", type: "number" },
                        yMinimum: { default: 0, description: "Minimum value on the Y-Axis", type: "number" },
                    },
                    required: ["xGraphId", "yGraphId", "label"],
                    type: "object",
                },
            ],
        },
    },
    showDevDebugOutput: {
        enum: ["none", "parsed", "raw", "both", "vscode"],
        default: "none",
        description: "Deprecated: Use debugFlags instead. Used to debug this extension.",
        deprecationMessage: "Please use 'debugFlags' to set individual debug modes.",
        type: "string",
    },
    showDevDebugTimestamps: {
        default: false,
        description: "Deprecated: Use debugFlags instead. Show timestamps when 'showDevDebugOutput' is enabled",
        deprecationMessage: "Please use 'debugFlags' to set individual debug modes.",
        type: "boolean",
    },
    debugFlags: {
        description: "Debug flags to debug this extension (mcu-debug); Causes additional output in Debug Console.",
        type: "object",
        default: {
            gdbTraces: false,
        },
        properties: {
            gdbTraces: { type: "boolean", default: false, description: "Enable GDB MI trace output" },
            liveGdbTraces: { type: "boolean", default: false, description: "Enable live GDB MI trace output during polling (only applies to built-in liveWatch/RTT)" },
            vscodeRequests: { type: "boolean", default: false, description: "Enable VSCode Request/Response trace output" },
            gdbTracesParsed: { type: "boolean", default: false, description: "Enable parsed GDB MI output" },
            timestamps: { type: "boolean", default: false, description: "Show timestamps in debug output" },
            pathResolution: { type: "boolean", default: false, description: "Show path resolution when reading symbols" },
            disableGdbTimeouts: { type: "boolean", default: false, description: "Disable GDB command timeouts. Helpful for debugging extension" },
        },
    },
    svdFile: {
        default: null,
        description: "This is for 'XPERIPHERALS' window provided by 'mcu-debug.peripheral-viewer'.",
        type: "string",
    },
    svdPath: {
        default: null,
        description: "This is for 'XPERIPHERALS' window provided by 'mcu-debug.peripheral-viewer' and 'Embedded Tools' Extension from Microsoft.",
        type: "string",
    },
    rttConfig: {
        type: "object",
        description: "SEGGER's Real Time Trace (RTT) and supported by JLink, OpenOCD and perhaps others in the future",
        default: {
            enabled: true,
            address: "auto",
            useBuiltinRTT: { enabled: true },
            decoders: [{ label: "", port: 0, type: "console" }],
        },
        properties: {
            enabled: { type: "boolean", description: "Enable/Disable RTT", default: false },
            address: { type: "string", description: "Address to start searching for the RTT control block.", default: "auto" },
            searchSize: { type: "number", description: "Number of bytes to search for the RTT control block.", multipleOf: 1, minimum: 16, default: 16 },
            searchId: { type: "string", description: "A string to search for to find the RTT control block.", default: "SEGGER RTT" },
            useBuiltinRTT: {
                type: "object",
                description:
                    "Use the built-in RTT support (recommended) especially with servers no native RTT support. If false, use gdb-server's RTT support, which may have better performance, but harder to setup.",
                properties: {
                    enabled: { type: "boolean", description: "Enable/Disable built-in RTT support", default: true },
                    hostName: { type: "string", description: "Host name to use for built-in RTT server.", default: "127.0.0.1" },
                    tcpPort: {
                        type: ["number", "null"],
                        description: "Fixed port number to use for built-in RTT server. If not set, a free port is chosen automatically.",
                        default: null,
                        minimum: 1024,
                        maximum: 65535,
                        multipleOf: 1,
                    },
                },
                default: { enabled: true },
            },
            pre_decoder: {
                type: "object",
                description: "Configuration for an external pre-decoder program to decode RTT channel data before being processed by other decoders.",
                properties: {
                    channels: {
                        type: ["array", "null"],
                        description: "RTT Channels to apply pre-decoder to. If not specified, all channels are used.",
                        items: { type: "number", maximum: 15, minimum: 0 },
                        default: null,
                    },
                    program: { type: "string", description: "Path to pre-decoder program.", default: "defmt-print" },
                    args: { type: "array", description: "Arguments to pass to pre-decoder program.", items: { type: "string" }, default: ["-e", "${executable}"] },
                    cwd: { type: "string", description: "Current working directory for pre-decoder program.", default: "${workspaceFolder}" },
                    env: { type: "object", description: "Additional environment variables for pre-decoder program.", additionalProperties: { type: "string" }, default: {} },
                },
                default: {
                    program: "defmt-print",
                    args: ["-e", "${executable}"],
                    cwd: "${workspaceFolder}",
                },
            },
            polling_interval: {
                type: ["number", "null"],
                description:
                    "Only for openocd & builtin RTT handlers. Number of milliseconds (> 0) to wait for check for data on out channels. Setting it lower than 50 may cause issues depending on your probe.",
                default: null,
                minimum: 1,
            },
            rtt_start_retry: { type: "number", description: "Keep trying to start RTT for OpenOCD until it succeeds.", default: 1000, minimum: 0 },
            clearSearch: { type: "boolean", description: "When true, clears the search-string.", default: true },
            decoders: {
                description: "SWO Decoder Configuration",
                items: {
                    anyOf: [
                        {
                            properties: {
                                label: { description: "A label for RTT Console", type: "string" },
                                port: { description: "RTT Channel Number (0 to 15)", default: 0, maximum: 15, minimum: 0, multipleOf: 1, type: "number" },
                                type: {
                                    enum: ["console", "binary"],
                                    default: "console",
                                    description: "'console' with text input/output, 'binary' is for converting byte stream to other data types",
                                    type: "string",
                                },
                                prompt: { description: "Prompt to use for RTT Console", type: "string", default: "" },
                                noprompt: { description: "Don't use a prompt for RTT Console", type: "boolean", default: false },
                                noclear: { description: "append to screen/logfile when another connection is made", type: "boolean", default: false },
                                logfile: { description: "log all raw data (input and output) to specified file", type: "string", default: "" },
                                timestamp: { description: "Add timestamps while printing for 'console' type.", type: "boolean", default: false },
                                encoding: { type: "string", description: "How binary data bytes are converted into a number.", default: "unsigned", enum: ["unsigned", "signed", "Q16.16", "float"] },
                                iencoding: { type: "string", description: "How keyboard input is encoded.", default: "utf8", enum: ["ascii", "utf8", "ucs2", "utf16le"] },
                                scale: { default: 1, description: "Binary only: This setting will scale the raw value.", type: "number" },
                                inputmode: { type: "string", description: "Experimental: 'disabled' means no stdin.", default: "cooked", enum: ["cooked", "raw", "rawecho", "disabled"] },
                            },
                            required: ["port"],
                            type: "object",
                        },
                        {
                            properties: {
                                encoding: {
                                    default: "unsigned",
                                    description: "This property is only used for binary and graph output formats.",
                                    enum: ["unsigned", "signed", "Q16.16", "float"],
                                    type: "string",
                                },
                                graphId: { description: "The identifier to use for this data in graph configurations.", type: "string" },
                                port: { description: "RTT Channel Number", maximum: 15, minimum: 0, type: "number" },
                                scale: { default: 1, description: "This setting will scale the raw value.", type: "number" },
                                type: { enum: ["graph"], type: "string" },
                            },
                            required: ["port", "graphId"],
                            type: "object",
                        },
                        {
                            properties: {
                                config: { additionalProperties: true, type: "object" },
                                decoder: { description: "Path to a javascript module to implement the decoding functionality.", type: "string" },
                                ports: { description: "RTT Channel Numbers", type: "array", items: { type: "number", maximum: 15, minimum: 0 } },
                                type: { enum: ["advanced"], type: "string" },
                            },
                            required: ["ports", "decoder"],
                            type: "object",
                        },
                    ],
                },
                type: "array",
            },
        },
    },
    swoConfig: {
        description: "Description of SWO can be configured. Also see our Wiki for details",
        properties: {
            cpuFrequency: { default: 0, description: "Target CPU frequency in Hz; 0 will attempt to automatically calculate.", type: "number" },
            enabled: { default: false, description: "Enable SWO decoding.", type: "boolean" },
            source: { type: "string", enum: ["probe", "socket", "serial", "file"], default: "probe", description: "Source for SWO data." },
            swoPath: { type: "string", default: "", description: 'Path name when source is "file" or "serial".' },
            swoPort: { type: "string", default: "", description: 'When server is "external" && source is "socket", port to connect to.' },
            decoders: {
                description: "SWO Decoder Configuration",
                items: {
                    anyOf: [
                        {
                            properties: {
                                label: { description: "A label for the output window.", type: "string" },
                                port: { description: "ITM Port Number", maximum: 31, minimum: 0, type: "number" },
                                showOnStartup: { description: "If true, switches to this output when starting a debug session.", type: "boolean" },
                                timestamp: { description: "Add timestamps while printing", type: "boolean", default: false },
                                type: { enum: ["console"], type: "string" },
                                encoding: { type: "string", default: "utf8", enum: ["ascii", "utf8", "ucs2", "utf16le"] },
                                logfile: { description: "log all raw data to specified file", type: "string", default: "" },
                            },
                            required: ["port"],
                            type: "object",
                        },
                        {
                            properties: {
                                encoding: {
                                    default: "unsigned",
                                    description: "This property is only used for binary and graph output formats.",
                                    enum: ["unsigned", "signed", "Q16.16", "float"],
                                    type: "string",
                                },
                                label: { description: "A label for the output window.", type: "string" },
                                port: { description: "ITM Port Number", maximum: 31, minimum: 0, type: "number" },
                                scale: { default: 1, description: "This setting will scale the raw value.", type: "number" },
                                type: { enum: ["binary"], type: "string" },
                                logfile: { description: "log all raw data to specified file", type: "string", default: "" },
                            },
                            required: ["port"],
                            type: "object",
                        },
                        {
                            properties: {
                                encoding: {
                                    default: "unsigned",
                                    description: "This property is only used for binary and graph output formats.",
                                    enum: ["unsigned", "signed", "Q16.16", "float"],
                                    type: "string",
                                },
                                graphId: { description: "The identifier to use for this data in graph configurations.", type: "string" },
                                port: { description: "ITM Port Number", maximum: 31, minimum: 0, type: "number" },
                                scale: { default: 1, description: "This setting will scale the raw value.", type: "number" },
                                type: { enum: ["graph"], type: "string" },
                                logfile: { description: "log all raw data to specified file", type: "string", default: "" },
                            },
                            required: ["port", "graphId"],
                            type: "object",
                        },
                        {
                            properties: {
                                config: { additionalProperties: true, type: "object" },
                                decoder: { description: "Path to a javascript module to implement the decoding functionality.", type: "string" },
                                ports: { description: "ITM Port Numbers", type: "array", items: { maximum: 31, minimum: 0, type: "number" } },
                                type: { enum: ["advanced"], type: "string" },
                            },
                            required: ["ports", "decoder"],
                            type: "object",
                        },
                    ],
                },
                type: "array",
            },
            swoFrequency: { default: 0, description: "SWO frequency in Hz; 0 will attempt to automatically calculate.", type: "number" },
            swoEncoding: { default: "uart", description: "BMP only: SWO encoding data used at the line level.", type: "string", enum: ["uart", "manchester"] },
        },
        required: [],
        type: "object",
    },
    ipAddress: {
        default: null,
        description: "IP Address for networked J-Link Adapter",
        pattern:
            "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$",
        type: "string",
    },
    serialNumber: {
        default: null,
        description: "J-Link or ST-LINK Serial Number - only needed if multiple J-Links/ST-LINKs are connected to the computer",
        type: "string",
    },
    interface: {
        default: "swd",
        description: "Debug Interface type to use for connections (defaults to SWD) - Used for J-Link, ST-LINK and BMP probes.",
        type: "string",
        enum: ["swd", "jtag", "cjtag"],
    },
    jlinkscript: {
        default: null,
        description: "J-Link script file - optional input file for customizing J-Link actions.",
        type: "string",
    },
    openOCDLaunchCommands: {
        default: [],
        description: "OpenOCD command(s) after configuration files are loaded (-c options)",
        items: { type: "string" },
        type: "array",
    },
    openOCDPreConfigLaunchCommands: {
        default: [],
        description: "OpenOCD command(s) before configuration files are loaded (-c options)",
        items: { type: "string" },
        type: "array",
    },
    configFiles: {
        description: "OpenOCD/PE GDB Server configuration file(s) to use when debugging (OpenOCD -f option)",
        items: { type: "string" },
        type: "array",
    },
    searchDir: {
        default: [],
        description: "OpenOCD directories to search for config files and scripts (-s option).",
        items: { type: "string" },
        type: "array",
    },
    v1: {
        default: false,
        description: "For st-util only. Set this to true if your debug probe is a ST-Link V1.",
        type: "boolean",
    },
    stlinkPath: {
        default: null,
        description: "Path to the ST-LINK_gdbserver executable.",
        type: "string",
    },
    stm32cubeprogrammer: {
        default: null,
        description: "This path is normally resolved to the installed STM32CubeIDE or STM32CubeProgrammer but can be overridden here.",
        type: "string",
    },
    targetId: {
        description: "On BMP this is the ID number that should be passed to the attach command (defaults to 1); for PyOCD this is the target identifier",
        type: ["string", "number"],
        anyOf: [{ type: "string" }, { type: "number", minimum: 1 }],
    },
    boardId: {
        description: "PyOCD Board Identifier. Needed if multiple compatible boards are connected.",
        type: "string",
    },
    cmsisPack: {
        description: "Path to a CMSIS-Pack file. Use to add extra device support.",
        type: "string",
    },
    BMPGDBSerialPort: {
        type: "string",
        description: "The serial port for the Black Magic Probe GDB Server.",
    },
    powerOverBMP: {
        type: "string",
        description: "Power up the board over Black Magic Probe.",
    },
};
