// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisassembleArguments } from "./DisassembleArguments";

export type DisassembleRequest = { req: string, seq: number, arguments: DisassembleArguments, };
