// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerInstruction } from "./SerInstruction";

/**
 * DisasmResponse is the response to a disassembly request, containing the disassembled instructions and
 * any relevant symbol information. It is designed to be compact for efficient transmission.
 *
 * There are two hashmaps for file and function names. They are actually global id's so they may look random
 * but they allow us to avoid sending the same file and function names repeatedly for every instruction, which
 * can save a lot of space in the response. These hashmaps come with every response so the client is not
 * expected to cache them across responses, but they may contain overlapping information with previous responses.
 * The client can choose to cache them if it wants, but it should not rely on them being the same across responses.
 */
export type DisasmResponse = { req: string, seq: bigint, file_table: { [key in number]: string }, func_table: { [key in number]: string }, instructions: Array<SerInstruction>, };
