// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalsResponse = { req: string, seq: bigint, globals: Array<[string, string]>, };
