// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SymbolLookupResponse = { req: string, seq: number, symbols: Array<[string, string]>, };
