// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SymbolLookupNameRequest = { req: string, seq: bigint, name: string, file_name: string | null, };
