name: 🐛 Bug Report
description: Report a bug to help us improve MCU-Debug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### 🛑 STOP! READ THIS FIRST 🛑
        Most issues cannot be solved without **Debug Console Logs**. 
        Please enable `"showDevDebugOutput": true` in your `launch.json` before submitting.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight Checklist
      options:
        - label: I have enabled verbose logging (`showDevDebugOutput: true`).
          required: true
        - label: I have attached the relevant section of the Debug Console log.
          required: true
        - label: I am using the latest version of the extension.
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us about the bug...
    validations:
      required: true

  - type: textarea
    id: debug-logs
    attributes:
      label: Debug Console Logs
      description: Paste the logs from the VS Code Debug Console here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: launch-json
    attributes:
      label: launch.json Configuration
      description: Your launch.json (remove any sensitive paths or passwords).
      render: json
    validations:
      required: true
