name: bug report
description: Report MCU-Debug bugs
title: "[bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: debug-console-logs
    attributes:
      label: Debug Console Logs
      render: shell
    validations:
      required: true

  - type: textarea
    id: launch-json
    attributes:
      label: launch.json
      render: json
    validations:
      required: true
