// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./JsonValue";
import type { PortAllocatorSpec } from "./PortAllocatorSpec";
import type { PortWaitMode } from "./PortWaitMode";

export type ControlMessage = { seq: number } & (
    | {
          method: "initialize";
          params: {
              /**
               * Token for authentication
               */
              token: string;
              /**
               * SemVer string representing the version
               */
              version: string;
              /**
               * Base directory unique-id of the remote launch dir for debugging
               */
              workspace_uid: string;
              /**
               * Unique identifier for the session
               */
              session_uid: string;
              /**
               * Port wait mode for this session
               */
              port_wait_mode: PortWaitMode | null;
          };
      }
    | {
          method: "allocatePorts";
          params: {
              /**
               * Number of consecutive ports needed
               */
              ports_spec: PortAllocatorSpec;
          };
      }
    | {
          method: "startGdbServer";
          params: {
              /**
               * Launch configuration arguments
               */
              config_args: JsonValue;
              /**
               * Path to the gdb-server executable on the host machine
               */
              server_path: string;
              /**
               * Arguments to launch the gdb-server with
               */
              server_args: Array<string>;
              /**
               * Environment variables for the gdb-server process
               */
              server_env: { [key in string]: string } | null;
              /**
               * Required: Regex patterns to identify the gdb-server process from its output (e.g. "Listening on port (\d+)"), used for auto-detecting the port if not specified in server_args
               */
              server_regexes: Array<string>;
          };
      }
    | { method: "endSession" }
    | { method: "streamStatus"; params: { stream_id: number } }
    | { method: "startStream"; params: { stream_id: number } }
    | { method: "duplicateStream"; params: { stream_id: number } }
    | { method: "heartbeat" }
    | { method: "syncFile"; params: { relative_path: string; content: Array<number> } }
);
