// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailablePort } from "../serial-helper/AvailablePort";
import type { SerialParams } from "../serial-helper/SerialParams";
import type { PortReserved } from "./PortReserved";
import type { SerialPortInfo } from "./SerialPortInfo";
import type { StreamStatus } from "./StreamStatus";

export type ControlResponseData =
    | { initialize: { version: string; server_cwd: string } }
    | { allocatePorts: { ports: Array<PortReserved> } }
    | { startGdbServer: { pid: number } }
    | { streamStatus: { stream_id: number; status: StreamStatus; msg_seq: number } }
    | "heartbeat"
    | {
          "serial.open": {
              path: string;
              /**
               * TCP port the direct bridge listens on (`transport == "direct"`).
               */
              tcp_port: number | null;
              /**
               * Funnel stream ID (`transport == "funnel"`).
               */
              channel_id: number | null;
          };
      }
    | "serial.close"
    | { "serial.listOpen": { ports: Array<SerialPortInfo> } }
    | { "serial.listAvailable": { ports: Array<AvailablePort> } }
    | {
          "serial.isOpen": {
              open: boolean;
              tcp_port: number | null;
              channel_id: number | null;
              params: SerialParams | null;
          };
      };
