// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortReserved } from "./PortReserved";
import type { StreamStatus } from "./StreamStatus";

export type ControlResponseData =
    | { initialize: { version: string; server_cwd: string } }
    | { allocatePorts: { ports: Array<PortReserved> } }
    | { startGdbServer: { pid: number } }
    | { streamStatus: { stream_id: number; status: StreamStatus; msg_seq: number } }
    | "heartbeat";
