// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `--status` reports about the executable a running proxy is serving from.
 *
 * The daemon answers this itself rather than leaving the caller to compare numbers,
 * because only the daemon knows what it started with, and it is the one process
 * guaranteed to be on the same filesystem as the file in question.
 */
export type ExeStatus = {
    /**
     * Path this proxy was launched from.
     */
    path: string;
    /**
     * The file's mtime when this proxy started, in epoch milliseconds, and the same
     * value rendered in local time.
     */
    started_with_mtime_ms: number | null;
    started_with_mtime: string;
    /**
     * What is at `path` right now. Differs from the above once the binary has been
     * replaced -- which is normal and expected during a build or a reinstall.
     */
    on_disk_mtime_ms: number | null;
    on_disk_mtime: string;
    /**
     * The question worth asking: **is this proxy serving code that is no longer on
     * disk?** True after a rebuild or a same-version reinstall, until the next launch
     * hands over to the replacement (see [`decide_handover`]). `false` when either
     * mtime is unknown -- absent evidence is not evidence.
     */
    replaced_since_start: boolean;
};
