// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailablePort } from "../serial-helper/AvailablePort";
import type { SerialErrorKind } from "../serial-helper/SerialErrorKind";

/**
 * Responses are different from events as they represent the result of a request, while events are
 * notifications from the server
 * */
export type ProxyServerEvents =
    | { event: "gdbServerLaunched"; params: { pid: number; port: number } }
    | { event: "gdbServerExited"; params: { pid: number; exit_code: number } }
    | { event: "streamReady"; params: { stream_id: number; port: number } }
    | { event: "streamClosed"; params: { stream_id: number } }
    | { event: "streamTimedOut"; params: { stream_id: number } }
    | { event: "serial.portError"; params: { path: string; kind: SerialErrorKind; msg: string } }
    | { event: "serial.availableChanged"; params: { revision: number; ports: Array<AvailablePort> } }
    | {
          event: "rttReady";
          params: {
              /**
               * Where the control block was found, for confirming it against the ELF symbol.
               */
              cb_address: string;
              /**
               * What the block itself says, which may be fewer than the channels that were asked for --
               * worth comparing, since a decoder naming a channel the firmware never allocated will
               * simply never produce anything.
               */
              up_channels: number;
              down_channels: number;
              /**
               * How long the search ran, in milliseconds. Almost always the firmware rather than us.
               */
              search_ms: number;
          };
      }
    | {
          event: "rttStats";
          params: {
              /**
               * Bytes delivered to the client, and bytes written to down channels.
               */
              bytes_up: number;
              bytes_down: number;
              /**
               * Drains that moved at least one byte.
               */
              drains: number;
              /**
               * Passes that found nothing. Climbing means the firmware had nothing for us, so throughput
               * is its production rate rather than our cost.
               */
              idle: number;
              /**
               * Passes skipped because the multiplexer would not let a packet out. Climbing means GDB's
               * traffic on the shared connection, not the probe.
               */
              gated: number;
              /**
               * Failed passes, and the split by cause -- one total cannot be acted on, because a
               * descriptor that failed validation, a server that mangled a reply and a read that timed
               * out are three unrelated problems. The Agent is the only side that still knows which.
               */
              errors: number;
              err_invalid: number;
              err_rejected: number;
              err_timeout: number;
              err_other: number;
              /**
               * Memory reads and writes issued. Their sum is round trips.
               */
              reads: number;
              writes: number;
              /**
               * Milliseconds since the control block was found, which is when the counters started.
               */
              elapsed_ms: number;
          };
      }
    | { event: "rttStopped"; params: { reason: string } };
