// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailablePort } from "../serial-helper/AvailablePort";
import type { SerialErrorKind } from "../serial-helper/SerialErrorKind";

/**
 * Responses are different from events as they represent the result of a request, while events are
 * notifications from the server
 * */
export type ProxyServerEvents =
    | { event: "gdbServerLaunched"; params: { pid: number; port: number } }
    | { event: "gdbServerExited"; params: { pid: number; exit_code: number } }
    | { event: "streamReady"; params: { stream_id: number; port: number } }
    | { event: "streamClosed"; params: { stream_id: number } }
    | { event: "streamTimedOut"; params: { stream_id: number } }
    | { event: "serial.portError"; params: { path: string; kind: SerialErrorKind; msg: string } }
    | { event: "serial.availableChanged"; params: { revision: number; ports: Array<AvailablePort> } }
    | {
          event: "rttReady";
          params: {
              /**
               * Where the control block was found, for confirming it against the ELF symbol.
               */
              cb_address: string;
              /**
               * What the block itself says, which may be fewer than the channels that were asked for --
               * worth comparing, since a decoder naming a channel the firmware never allocated will
               * simply never produce anything.
               */
              up_channels: number;
              down_channels: number;
              /**
               * How long the search ran, in milliseconds. Almost always the firmware rather than us.
               */
              search_ms: number;
          };
      }
    | { event: "rttStopped"; params: { reason: string } };
