// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One RTT channel and the funnel stream its data arrives on.
 */
export type RttChannelStream = { channel: number; stream_id: number };
