// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Agent needs to run RTT, from the client's `rttConfig`.
 */
export type RttStartConfig = {
    /**
     * Absolute address of `_SEGGER_RTT`, as a hex string (`"0x20000000"`).
     *
     * **Already resolved.** `rttConfig.address: "auto"` is turned into a number by the debug
     * adapter from the ELF symbol table, which is the only side that has one -- so no symbol
     * lookup happens in the Agent.
     */
    cb_address: string;
    /**
     * The id the firmware writes last, normally `"SEGGER RTT"`. Truncated to 16 bytes.
     */
    search_id: string;
    /**
     * True for a big-endian target. From `TargetInfo.endianness`, which only the adapter knows.
     */
    big_endian: boolean;
    /**
     * Up channels (target to host) to drain.
     */
    up_channels: Array<number>;
    /**
     * Down channels (host to target) to accept input for.
     */
    down_channels: Array<number>;
    /**
     * How long to wait after a pass that moved nothing. The engine polls back to back while data
     * is flowing, so this is an idle interval and not a rate limit.
     */
    poll_interval_ms: number | null;
    /**
     * Cap on one channel's drain, so a full buffer cannot hold the shared RSP connection while
     * GDB waits behind it.
     */
    max_bytes_per_drain: number | null;
    /**
     * How often to send `rttStats`, or `None` for never.
     *
     * Asked for by the client rather than decided here, because the engine's counters are only half
     * of a throughput measurement -- the consumer's own line is the other half, and the two are
     * meaningless apart. So this rides the same per-decoder `stats` switch that turns that line on,
     * and carries its interval, which is what keeps both describing the same window.
     */
    stats_interval_ms: number | null;
};
