// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerialParams } from "../serial-helper/SerialParams";

/**
 * One entry in a `serial.listOpen` response.
 */
export type SerialPortInfo = {
    /**
     * Current configuration (includes the `transport` field).
     */
    params: SerialParams;
    /**
     * TCP port the direct bridge is listening on, if any direct client asked for one.
     */
    tcp_port: number | null;
    /**
     * Funnel stream IDs attached to this port, ascending. Plural because transports
     * are additive: a port can carry several funnel channels (one per client, plus
     * one per reconnect) at the same time as a direct bridge.
     */
    channel_ids: Array<number>;
};
