// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerialParams } from "../serial-helper/SerialParams";

/**
 * One entry in a `serial.listOpen` response.
 */
export type SerialPortInfo = { params: SerialParams; tcp_port: number };
