// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of one open port for `--status`.
 */
export type SerialStatus = {
    path: string;
    /**
     * TCP port of the direct bridge, if one is up.
     */
    tcp_port: number | null;
    /**
     * Sessions holding a direct reference.
     */
    direct_refs: number;
    /**
     * Funnel channels attached.
     */
    channels: number;
    /**
     * Total attached client sinks, across both transports. Larger than `channels`
     * when direct clients are connected to the bridge.
     */
    clients: number;
};
