// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent-side debug switches that belong to **one session**, not to the proxy.
 *
 * This distinction is the whole reason the type exists. A proxy is a shared daemon
 * serving several sessions and several clients at once, so a process-wide command-line
 * flag cannot express "trace *this* debug session" — turning tracing on would trace
 * everybody's, and turning the mux off would turn it off for someone else's session
 * mid-debug. These arrive on `initialize`, which is per connection and therefore per
 * session, and they override the corresponding `--rsp-*` defaults on the command line.
 *
 * Only the flags the Agent can act on are on the wire. The rest of `debugFlags` —
 * `gdbTraces`, `timestamps` and friends — control the extension's own output and have no
 * meaning here, so the client maps across the two it needs rather than forwarding the
 * object wholesale. That also keeps this in the protocol's snake_case rather than
 * importing launch.json's camelCase into it.
 */
export type SessionDebugFlags = {
    /**
     * RSP packet trace level for this session's muxed streams: `off`, `packets` or `all`.
     * Unrecognised values mean `off` — a typo in a launch configuration must not fail the
     * session. `None` defers to `--rsp-trace`.
     */
    rsp_trace: string | null;
    /**
     * Whether the RSP multiplexer owns this session's controller gdb streams. `None`
     * defers to the proxy's own default (on, unless it was started `--no-rsp-mux`).
     */
    rsp_mux: boolean | null;
    /**
     * Override what the Agent believes this gdb-server can do: `full`, `haltedOnly` or
     * `unsupported`. `None`, or anything unrecognised, uses the measured default for the
     * `servertype` (`RspCaps`/`ServerTier::from_server_type`).
     *
     * Exists because the compatibility matrix in §7 has one server measured and four to go, and
     * without a way to say "try it" there is no way to measure the rest on real hardware.
     */
    rsp_tier: string | null;
};
