// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExeStatus } from "./ExeStatus";
import type { SerialStatus } from "./SerialStatus";

export type StatusInfo = {
    pid: number;
    version: string;
    port: number;
    instance: string;
    state: string;
    /**
     * Active refs = live sessions + (window keep-alive, if `--heartbeat`).
     */
    active_refs: number;
    uptime_secs: number;
    /**
     * Every address this proxy accepts on. `default` so a status reply from an older
     * proxy (during an upgrade handover) still parses.
     */
    hosts: Array<string>;
    /**
     * Serial ports this proxy currently holds open. `default` so a status reply
     * from an older proxy (during an upgrade handover) still parses.
     */
    serial_ports: Array<SerialStatus>;
    /**
     * Which executable this proxy is serving from, and whether that file has been
     * replaced since it started — the difference between "running the build you think
     * it is" and "still serving code that no longer exists on disk". `default` so a
     * reply from an older proxy (which happens mid-handover) still parses.
     */
    exe: ExeStatus;
};
