// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusInfo } from "./StatusInfo";

/**
 * `--status` output: every running instance, with a `count` (which replaces the
 * old boolean `ok` — a per-instance concept that had no meaning across many).
 *
 * Exported to TypeScript because the extensions parse this document: `proxyStatus` on the
 * proxy side runs `--status` and hands the JSON to the main extension. Hand-writing the
 * interface over there is how the two drift — this is the only wire type on the admin
 * channel that TS reads, and it should stay generated.
 */
export type StatusReport = {
    /**
     * Number of instances that answered a status query (i.e. are actually running).
     */
    count: number;
    instances: Array<StatusInfo>;
};
