// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Uniform representation of an available serial port returned by all
 * platform-specific enumerators. `description` is informational only —
 * never used as an identity key. Port paths are the stable key.
 */
export type AvailablePort = { path: string; description: string; vid: number | null; pid: number | null };
