// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flow control mode — mirrors `serialport::FlowControl` but is JSON-serializable.
 */
export type FlowControl = "none" | "software" | "hardware";
