// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parity mode — mirrors `serialport::Parity` but is JSON-serializable.
 */
export type Parity = "none" | "odd" | "even";
