// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of a post-open fatal serial error.
 *
 * Sent as part of a `serial.portError` async event. Client code branches on
 * this value; `msg` in [`PortErrorEvent`] is human-readable only.
 */
export type SerialErrorKind = "disconnected" | "io_error" | "permission_lost" | "timeout";
