// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowControl } from "./FlowControl";
import type { Parity } from "./Parity";
import type { SerialTransport } from "./SerialTransport";
import type { StopBits } from "./StopBits";

/**
 * Parameters to open or reconfigure a serial port.
 *
 * Specify the device via `path` (direct path or glob), `serial` (USB serial
 * number), or `vid`/`pid` (USB vendor/product IDs in hex, e.g. `"0x0483"`).
 * `serial` is the most stable identifier in lab environments with multiple
 * boards. All baud/framing fields default to 115200 8N1 no flow control.
 */
export type SerialParams = {
    /**
     * Direct device path or glob (e.g. `/dev/ttyUSB0`, `/dev/tty.usbserial-*`, `COM3`).
     */
    path?: string | null;
    /**
     * USB serial number. Stable across reconnects and reboots.
     */
    serial?: string | null;
    /**
     * USB vendor ID in hex (e.g. `"0x0483"`). Used with `pid` when `serial` is unavailable.
     */
    vid?: string | null;
    /**
     * USB product ID in hex (e.g. `"0x374b"`). Used with `vid` when `serial` is unavailable.
     */
    pid?: string | null;
    baud_rate: number;
    data_bits: number;
    stop_bits: StopBits;
    parity: Parity;
    flow_control: FlowControl;
    /**
     * Transport used to open this port. Defaults to `direct` so that existing
     * callers that do not set this field get the original TCP-bridge behaviour.
     */
    transport: SerialTransport;
    /**
     * Optional frontend-only serial logging path. Kept in schema so generated
     * TypeScript stays in sync with UI usage.
     */
    log_file?: string | null;
    /**
     * Optional frontend-only terminal input mode hint.
     */
    input_mode?: string | null;
};
