// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport channel the client uses to receive serial bytes.
 *
 * Supplied in `serial.open` requests. Returned in `serial.listOpen` and
 * `serial.isOpen` responses to describe how the port is currently connected.
 */
export type SerialTransport = "direct" | "funnel";
