// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowControl } from "./FlowControl";
import type { Parity } from "./Parity";
import type { SerialTransport } from "./SerialTransport";
import type { StopBits } from "./StopBits";

/**
 * Parameters to open or reconfigure a serial port.
 *
 * All fields except `path` have defaults (115200 8N1 no flow control), so
 * a `serial.open` request only needs to supply `path`. On `serial.listOpen`
 * responses all fields are always present.
 */
export type SerialParams = {
    path: string;
    baud_rate: number;
    data_bits: number;
    stop_bits: StopBits;
    parity: Parity;
    flow_control: FlowControl;
    /**
     * Transport used to open this port. Defaults to `direct` so that existing
     * callers that do not set this field get the original TCP-bridge behaviour.
     */
    transport: SerialTransport;
    tcp_port?: number;
    decoders?: any;
};
