// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stop-bit count — mirrors `serialport::StopBits` but is JSON-serializable.
 */
export type StopBits = "one" | "one_point_five" | "two";
