// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events generated by the helper process and sent to the DA.
 * Uses internally-tagged enum serialization so each variant has a 'type' field.
 * In TypeScript, this becomes a discriminated union for type-safe event handling.
 */
export type HelperEvent = { "type": "SymbolTableReady", session_id: string, version: string, } | { "type": "DisassemblyReady", session_id: string, instruction_count: number, } | { "type": "RTTFound", session_id: string, address: string, num_up_channels: number, num_down_channels: number, } | { "type": "Progress", session_id: string, operation: string, percentage: number | null, message: string | null, } | { "type": "Output", session_id: string, category: string, message: string, } | { "type": "Error", session_id: string, code: string | null, message: string, details: string | null, } | { "type": "Log", session_id: string, level: string, message: string, };
