// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The SerInstruction is intentionally compact and uses short field names to minimize
 * the size of the JSON response for disassembly requests, which can be quite large.
 */
export type SerInstruction = { a: string, b: string, i: string, f: number, F: number, sl: number, el: number, };
